version: '3'
services:
  redis:
    image: redis:5.0.5-alpine
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
  mkpay-db:
    image: "postgres"
    container_name: mkpay-db
    env_file:
      - database.env
    volumes:
      - mkpay-user:/var/lib/postgresql/data
      - ./schema/:/usr/share/db-schema
    ports:
      - '5433:5432'
  mkpay-db-testing:
    image: "postgres"
    container_name: mkpay-db-testing
    env_file:
      - database_testing.env
    volumes:
      - mkpay-user-testing:/var/lib/postgresql/data
      - ./schema/:/usr/share/db-schema
    ports:
      - '5434:5432'
volumes: 
  redis:
  mkpay-user:
  mkpay-user-testing: